// Code generated by MockGen. DO NOT EDIT.
// Source: trpc_hello.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=trpc_hello_mock.go -package=trpchello --source=trpc_hello.trpc.go -self_package=github.com/trpcproto/trpchello
//
// Package trpchello is a generated GoMock package.
package trpchello

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockHelloServiceService is a mock of HelloServiceService interface.
type MockHelloServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockHelloServiceServiceMockRecorder
}

// MockHelloServiceServiceMockRecorder is the mock recorder for MockHelloServiceService.
type MockHelloServiceServiceMockRecorder struct {
	mock *MockHelloServiceService
}

// NewMockHelloServiceService creates a new mock instance.
func NewMockHelloServiceService(ctrl *gomock.Controller) *MockHelloServiceService {
	mock := &MockHelloServiceService{ctrl: ctrl}
	mock.recorder = &MockHelloServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloServiceService) EXPECT() *MockHelloServiceServiceMockRecorder {
	return m.recorder
}

// HandleFirst mocks base method.
func (m *MockHelloServiceService) HandleFirst(ctx context.Context, req *HelloReq) (*HelloRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleFirst", ctx, req)
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleFirst indicates an expected call of HandleFirst.
func (mr *MockHelloServiceServiceMockRecorder) HandleFirst(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFirst", reflect.TypeOf((*MockHelloServiceService)(nil).HandleFirst), ctx, req)
}

// HandleSeconds mocks base method.
func (m *MockHelloServiceService) HandleSeconds(ctx context.Context, req *HelloSecondReq) (*HelloSecondRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSeconds", ctx, req)
	ret0, _ := ret[0].(*HelloSecondRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleSeconds indicates an expected call of HandleSeconds.
func (mr *MockHelloServiceServiceMockRecorder) HandleSeconds(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSeconds", reflect.TypeOf((*MockHelloServiceService)(nil).HandleSeconds), ctx, req)
}

// HandleThird mocks base method.
func (m *MockHelloServiceService) HandleThird(ctx context.Context, req *HelloThirdReq) (*HelloThirdRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleThird", ctx, req)
	ret0, _ := ret[0].(*HelloThirdRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleThird indicates an expected call of HandleThird.
func (mr *MockHelloServiceServiceMockRecorder) HandleThird(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleThird", reflect.TypeOf((*MockHelloServiceService)(nil).HandleThird), ctx, req)
}

// MockHelloServiceClientProxy is a mock of HelloServiceClientProxy interface.
type MockHelloServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockHelloServiceClientProxyMockRecorder
}

// MockHelloServiceClientProxyMockRecorder is the mock recorder for MockHelloServiceClientProxy.
type MockHelloServiceClientProxyMockRecorder struct {
	mock *MockHelloServiceClientProxy
}

// NewMockHelloServiceClientProxy creates a new mock instance.
func NewMockHelloServiceClientProxy(ctrl *gomock.Controller) *MockHelloServiceClientProxy {
	mock := &MockHelloServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockHelloServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloServiceClientProxy) EXPECT() *MockHelloServiceClientProxyMockRecorder {
	return m.recorder
}

// HandleFirst mocks base method.
func (m *MockHelloServiceClientProxy) HandleFirst(ctx context.Context, req *HelloReq, opts ...client.Option) (*HelloRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HandleFirst", varargs...)
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleFirst indicates an expected call of HandleFirst.
func (mr *MockHelloServiceClientProxyMockRecorder) HandleFirst(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFirst", reflect.TypeOf((*MockHelloServiceClientProxy)(nil).HandleFirst), varargs...)
}

// HandleSeconds mocks base method.
func (m *MockHelloServiceClientProxy) HandleSeconds(ctx context.Context, req *HelloSecondReq, opts ...client.Option) (*HelloSecondRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HandleSeconds", varargs...)
	ret0, _ := ret[0].(*HelloSecondRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleSeconds indicates an expected call of HandleSeconds.
func (mr *MockHelloServiceClientProxyMockRecorder) HandleSeconds(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSeconds", reflect.TypeOf((*MockHelloServiceClientProxy)(nil).HandleSeconds), varargs...)
}

// HandleThird mocks base method.
func (m *MockHelloServiceClientProxy) HandleThird(ctx context.Context, req *HelloThirdReq, opts ...client.Option) (*HelloThirdRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HandleThird", varargs...)
	ret0, _ := ret[0].(*HelloThirdRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleThird indicates an expected call of HandleThird.
func (mr *MockHelloServiceClientProxyMockRecorder) HandleThird(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleThird", reflect.TypeOf((*MockHelloServiceClientProxy)(nil).HandleThird), varargs...)
}
