// Code generated by trpc-go/trpc-cmdline v1.0.7. DO NOT EDIT.
// source: trpc_hello.proto

package trpchello

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// HelloServiceService defines service.
type HelloServiceService interface {
	HandleFirst(ctx context.Context, req *HelloReq) (*HelloRsp, error)

	HandleSeconds(ctx context.Context, req *HelloSecondReq) (*HelloSecondRsp, error)

	HandleThird(ctx context.Context, req *HelloThirdReq) (*HelloThirdRsp, error)
}

func HelloServiceService_HandleFirst_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(HelloServiceService).HandleFirst(ctx, reqbody.(*HelloReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func HelloServiceService_HandleSeconds_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloSecondReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(HelloServiceService).HandleSeconds(ctx, reqbody.(*HelloSecondReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func HelloServiceService_HandleThird_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloThirdReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(HelloServiceService).HandleThird(ctx, reqbody.(*HelloThirdReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// HelloServiceServer_ServiceDesc descriptor for server.RegisterService.
var HelloServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpchello.HelloService",
	HandlerType: ((*HelloServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpchello.HelloService/HandleFirst",
			Func: HelloServiceService_HandleFirst_Handler,
		},
		{
			Name: "/trpchello.HelloService/HandleSeconds",
			Func: HelloServiceService_HandleSeconds_Handler,
		},
		{
			Name: "/trpchello.HelloService/HandleThird",
			Func: HelloServiceService_HandleThird_Handler,
		},
	},
}

// RegisterHelloServiceService registers service.
func RegisterHelloServiceService(s server.Service, svr HelloServiceService) {
	if err := s.Register(&HelloServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("HelloService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedHelloService struct{}

func (s *UnimplementedHelloService) HandleFirst(ctx context.Context, req *HelloReq) (*HelloRsp, error) {
	return nil, errors.New("rpc HandleFirst of service HelloService is not implemented")
}
func (s *UnimplementedHelloService) HandleSeconds(ctx context.Context, req *HelloSecondReq) (*HelloSecondRsp, error) {
	return nil, errors.New("rpc HandleSeconds of service HelloService is not implemented")
}
func (s *UnimplementedHelloService) HandleThird(ctx context.Context, req *HelloThirdReq) (*HelloThirdRsp, error) {
	return nil, errors.New("rpc HandleThird of service HelloService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// HelloServiceClientProxy defines service client proxy
type HelloServiceClientProxy interface {
	HandleFirst(ctx context.Context, req *HelloReq, opts ...client.Option) (rsp *HelloRsp, err error)

	HandleSeconds(ctx context.Context, req *HelloSecondReq, opts ...client.Option) (rsp *HelloSecondRsp, err error)

	HandleThird(ctx context.Context, req *HelloThirdReq, opts ...client.Option) (rsp *HelloThirdRsp, err error)
}

type HelloServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewHelloServiceClientProxy = func(opts ...client.Option) HelloServiceClientProxy {
	return &HelloServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *HelloServiceClientProxyImpl) HandleFirst(ctx context.Context, req *HelloReq, opts ...client.Option) (*HelloRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpchello.HelloService/HandleFirst")
	msg.WithCalleeServiceName(HelloServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("HelloService")
	msg.WithCalleeMethod("HandleFirst")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *HelloServiceClientProxyImpl) HandleSeconds(ctx context.Context, req *HelloSecondReq, opts ...client.Option) (*HelloSecondRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpchello.HelloService/HandleSeconds")
	msg.WithCalleeServiceName(HelloServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("HelloService")
	msg.WithCalleeMethod("HandleSeconds")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloSecondRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *HelloServiceClientProxyImpl) HandleThird(ctx context.Context, req *HelloThirdReq, opts ...client.Option) (*HelloThirdRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpchello.HelloService/HandleThird")
	msg.WithCalleeServiceName(HelloServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("HelloService")
	msg.WithCalleeMethod("HandleThird")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloThirdRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
